BEGIN TRANSACTION;
DROP TABLE IF EXISTS "Hosts";
CREATE TABLE IF NOT EXISTS "Hosts" (
    "id"    INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
    "ip"    TEXT NOT NULL,
    "mac"   TEXT NOT NULL,
    "vendor"    TEXT NOT NULL,
    "description"   TEXT,
    "date"  TEXT NOT NULL,
    "network"   TEXT NOT NULL
);
DROP TABLE IF EXISTS "Datetime";
CREATE TABLE IF NOT EXISTS "Datetime" (
    "id"    INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
    "date"  TEXT NOT NULL UNIQUE
);
INSERT INTO Datetime(id, date) VALUES (1, "trash");
CREATE TABLE IF NOT EXISTS "Description" (
    "mac"    TEXT NOT NULL PRIMARY KEY UNIQUE,
    "description"  TEXT NOT NULL UNIQUE
);
COMMIT;
